version: "3.7"
services:
  api_service:
    restart: always
    build:
      context: .
      dockerfile: Dockerfile
    depends_on:
      - mongo_db

  mongo_db:
    image: "mongo:4.4.3"
    restart: always
    ports:
      - 27017:27017